name: ROS2 Foxy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: setup ROS2
        uses: ros-tooling/setup-ros@v0.4
        with:
          use-ros2-testing: true  # remove this once vrpn package goes into foxy index
          required-ros-distributions: foxy
      - name: install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-11-jdk python3-pip python3-colcon-common-extensions
          version: rolling-1.0
      - name: install pip dependencies
        run: |
          sudo pip3 install -U empy pyros-genmsg setuptools
      - name: install Fast-DDS-Gen
        run: |
          git clone --recursive https://github.com/eProsima/Fast-DDS-Gen.git -b v1.0.4 ~/Fast-RTPS-Gen
          sed -i 's/gradle-.\..\../gradle-6\.8\.3/g' ~/Fast-RTPS-Gen/gradle/wrapper/gradle-wrapper.properties
          cd ~/Fast-RTPS-Gen
          ./gradlew assemble && sudo env "PATH=$PATH" ./gradlew install
      - name: ROS2 build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: asl_flight2
          target-ros2-distro: foxy
          vcs-repo-file-url: https://raw.githubusercontent.com/StanfordASL/asl_flight2/main/.github/ros2.repos
